/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;
import dataaccessobjects.Userdao;
import model.User;
import dataaccessobjects.*;

/**
 *
 * @author TOMMOGO
 */
public class ChangesecurityQuestion extends javax.swing.JFrame {

    public String UserEmail;

    /**
     * Creates new form ChangesecurityQuestion
     */
    public ChangesecurityQuestion() {
        initComponents();
    }

    public ChangesecurityQuestion(String Email) {
        initComponents();
        UserEmail = Email;
        txtOld.setEditable(false);
        updatebtn.setEnabled(false);
    }

    public void validatefields() {
        String Email=txtmail.getText();
        String Password = txtpass.getText();
        String SecurityQuestion = txtNew.getText();
        String Answer = txtnewAnswer.getText();
        if (!Email.equals("")&& !Password.equals("") && !SecurityQuestion.equals("") && !Answer.equals("")) {
            
            //databaseoperation.setDataorDelete("update Users set SecurityQuestion ='"+SecurityQuestion+"' where Password='"+Password+"'", "Security Question changed Successfully");
            updatebtn.setEnabled(true);
        } else {
            updatebtn.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        txtOld = new javax.swing.JTextField();
        txtNew = new javax.swing.JTextField();
        txtnewAnswer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        checkboxpass = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestobeused/small-page-background.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestobeused/cafehome.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestobeused/change Security Question.png"))); // NOI18N
        jLabel1.setText("Change Security Question");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestobeused/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Old Security Question");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Security Question");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Answer");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        updatebtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(0, 0, 0));
        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestobeused/save.png"))); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        clearbtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        clearbtn.setForeground(new java.awt.Color(0, 0, 0));
        clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestobeused/clear.png"))); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));
        getContentPane().add(txtOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 260, -1));

        txtNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewKeyReleased(evt);
            }
        });
        getContentPane().add(txtNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 260, -1));

        txtnewAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnewAnswerKeyReleased(evt);
            }
        });
        getContentPane().add(txtnewAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 260, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpassKeyReleased(evt);
            }
        });
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 260, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        getContentPane().add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 260, -1));

        checkboxpass.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        checkboxpass.setForeground(new java.awt.Color(255, 255, 255));
        checkboxpass.setText("Show Password");
        checkboxpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxpassActionPerformed(evt);
            }
        });
        getContentPane().add(checkboxpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestobeused/small-page-background.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 660, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        //new loginPage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        new ChangesecurityQuestion().setVisible(true);
//        txtOld.setText("");
//        txtNew.setText("");
//        txtConfirm.setText("");
//        
    }//GEN-LAST:event_clearbtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        validatefields();
        User user=Userdao.getSecurityQuestion(UserEmail);
        txtOld.setText(user.getSecurityQuestion());
    }//GEN-LAST:event_formComponentShown

    private void txtNewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewKeyReleased
        // TODO add your handling code here:
        validatefields();
    }//GEN-LAST:event_txtNewKeyReleased

    private void txtnewAnswerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnewAnswerKeyReleased
        // TODO add your handling code here:
        validatefields();
    }//GEN-LAST:event_txtnewAnswerKeyReleased

    private void txtpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyReleased
        // TODO add your handling code here:
        validatefields();
    }//GEN-LAST:event_txtpassKeyReleased

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        String Email=txtmail.getText();
        String Password = txtpass.getText();
        String SecurityQuestion = txtNew.getText();
        String Answer = txtnewAnswer.getText();
        Userdao.ChangeSecurityQuestion(Email, Password, SecurityQuestion, Answer);
        setVisible(false);
        new ChangesecurityQuestion().setVisible(true);
    }//GEN-LAST:event_updatebtnActionPerformed

    private void checkboxpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxpassActionPerformed
        // TODO add your handling code here:
        if(checkboxpass.isSelected()){
            txtpass.setEchoChar((char)0);
            
        }
        else{
            txtpass.setEchoChar(('*'));}
    }//GEN-LAST:event_checkboxpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangesecurityQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangesecurityQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangesecurityQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangesecurityQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangesecurityQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkboxpass;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtNew;
    private javax.swing.JTextField txtOld;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtnewAnswer;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
