/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;

import javax.swing.table.DefaultTableModel;
import dataaccessobjects.databaseoperation;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author TOMMOGO
 */
public class VerifyUser extends javax.swing.JFrame {

    /**
     * Creates new form VerifyUser
     */
    public VerifyUser() {
        initComponents();
    }

    public void getAllRecords(String Email) {
//        DefaultTableModel dtm=(DefaultTableModel) txtTable.getModel();
//        dtm.setRowCount(1);
//        ArrayList<User> list=Userdao.getAllRecords(Email);
//        Iterator<User> itr=list.iterator();
//        while(itr.hasNext()){
//            User userObj=itr.next();
//            if(!userObj.getEmail().equals("tommogobsd@gmail")){
//            
//                dtm.addRow(new Object[]{userObj.getName(),userObj.getEmail(),userObj.getPhone(),userObj.getAddress(),userObj.getSecurityQuestion(),userObj.getStatus()});
//            }
//        }
        ResultSet rs = databaseoperation.getData("select *from Users");
        DefaultTableModel model = (DefaultTableModel) txtTable.getModel();
        model.setRowCount(0);
        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(6), rs.getString(8), rs.getString(8),});
                //rs.close();
            }
            rs.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestobeused/cafehome.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestobeused/verify users_1.png"))); // NOI18N
        jLabel1.setText("Verify User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestobeused/close.png"))); // NOI18N
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestobeused/search.png"))); // NOI18N
        jLabel2.setText("Search");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 254, -1));

        txtTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Phone", "Address", "Security Question", "Status"
            }
        ));
        txtTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtTable);
        if (txtTable.getColumnModel().getColumnCount() > 0) {
            txtTable.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 700, 270));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("*Click On Row To Change Status");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestobeused/search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestobeused/small-page-background.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 700, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new HomePage().setVisible(true);
    }//GEN-LAST:event_btncloseActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        getAllRecords("");
//ResultSet rs=databaseoperation.getData("select *from Users");
//        DefaultTableModel model=(DefaultTableModel)txtTable.getModel();
//        model.setRowCount(0);
//        try{
//            while (rs.next()){
//                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(7),rs.getString(8),});
//                //rs.close();
//            }
//            rs.close();
//        }
//        catch(SQLException e){
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_formComponentShown

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here
        String Email = txtEmail.getText();
        getAllRecords(Email);
//ResultSet rs=databaseoperation.getData("select *from Users");
//        DefaultTableModel model=(DefaultTableModel)txtTable.getModel();
//        model.setRowCount(0);
//        try{
//            while (rs.next()){
//                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(7),rs.getString(8),});
//                //rs.close();
//            }
//            rs.close();
//        }
//        catch(SQLException e){
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTableMouseClicked
        // TODO add your handling code here:
//        int index=txtTable.getSelectedRow();
//        TableModel model= txtTable.getModel();
//        String Email=model.getValueAt(index, 2).toString();
//        String Status=model.getValueAt(index, 6).toString();
//        if(Status.equals("true"))
//            Status="false";
//        else
//            Status="true";
//        int y=JOptionPane.showConfirmDialog(null,"Confirm you want to change Status of '"+Email+"'","Select",JOptionPane.YES_NO_OPTION);
//if(y==0)
//{
//    Userdao.Changestatus(Email, Status);
//    setVisible(false);
//    new VerifyUser().setVisible(true);
        //System.exit(0);        // TODO add your handling code here:
//    }
        int index = txtTable.getSelectedRow();
        TableModel model = txtTable.getModel();
        String Email = model.getValueAt(index, 1).toString();
        String Status = model.getValueAt(index, 5).toString();
        JOptionPane.showMessageDialog(null, Status);
        if (Status.equals("true")) {
            Status = "false";
            try {
                int a = JOptionPane.showConfirmDialog(null, "Do you want to the Status of" + Email + "", "Select", JOptionPane.YES_NO_OPTION);
                if (a == 0) {
                    databaseoperation.setDataorDelete("update users set Status='" + Status + "' where Email='" + Email + "'", "Status Changed Successfully");
                    setVisible(false);
                    new VerifyUser().setVisible(true);
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } 
        else{
            Status = "true";
            try {
                int a = JOptionPane.showConfirmDialog(null, "Do you want to the Status of" + Email + "", "Select", JOptionPane.YES_NO_OPTION);
                if (a == 0) {
                    databaseoperation.setDataorDelete("update users set Status='" + Status + "' where Email='" + Email + "'", "Status Changed Successfully");
                    setVisible(false);
                    new VerifyUser().setVisible(true);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_txtTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String NameorEmail = txtEmail.getText();
        ResultSet rs = databaseoperation.getData("select *from users where Name like '%" + NameorEmail + "%' or Email like '%" + NameorEmail + "%'");
        DefaultTableModel model = (DefaultTableModel) txtTable.getModel();
        model.setRowCount(0);
        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(6), rs.getString(8),});

            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerifyUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTable txtTable;
    // End of variables declaration//GEN-END:variables
}
